name: Generate Snake Animation

on:
  schedule:
    # Runs at midnight daily
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3.0.0

        with:
          github_user_name: AthulKrishna2501
          outputs: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg

      - name: Push Generated Snake
        run: |
          mkdir -p output
          mv dist/snake.svg output/github-contribution-grid-snake.svg
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generated GitHub contribution grid snake animation"
          git push
