name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 20 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: AthulKrishna2501
          outputs: dist/snake.svg
      - name: Commit Snake Animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git commit -m "Updated snake animation" || echo "No changes to commit"
      - name: Push Snake Animation
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: main
          force: true
